
inherit_from: .rubocop_todo.yml

require: rubocop-performance

AllCops:
  Exclude:
    - 'bin/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'public/**/*'
