sudo: required
dist: trusty
language: ruby
cache: bundler
addons:
  firefox: latest
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.0
script:
  - 'bundle exec rubocop -D'
  - 'bundle exec rails test'
  - 'bundle exec rails test:system'
