# Config file example (intendation of sub-tags required):

"nvidia": "Please read this guide: <a href='http://en.opensuse.org/Nvidia'>en.opensuse.org/Nvidia</a> for instructions how to configure your NVIDIA graphics card."
"google earth": "Google earth is available from google's website: <a href='http://earth.google.de/download-earth.html'>http://earth.google.de/download-earth.html</a>"
"kde4": "kde4 is not a package name. Please try searching for kdebase4 for example."
"vlc": "To get a vlc package that is capable of playing all videos, please use the one from <a href='http://packman.links2linux.com/package/vlc'>packman</a>."
"skype": "Please get skype from <a href='http://www.skype.com'>skype.com</a>."
"dropbox": "For the original dropbox client, please check <a href='http://www.dropbox.com'>dropbox.com</a>. You might also want to consider the open-source alternative <a href='http://owncloud.org'>ownCloud</a>!"
"chrome": "The open source version of Google's browser is called chromium. Get it <a href='http://software.opensuse.org/package/chromium'>here</a>."
"mplayer": "To get a mplayer package that is capable of playing all videos, please use the one from <a href='http://packman.links2linux.com/package/mplayer'>packman</a>."
