# Config file example (intendation of sub-tags required):

"nvidia": "Please read this guide: <a href='http://en.opensuse.org/Nvidia'>en.opensuse.org/Nvidia</a> for instructions how to configure your NVIDIA graphics card."
"broadcom": "To install your broadcom wireless adapter, you probably need the proprietary drivers, available from <a href='http://packman.links2linux.com/package/broadcom-wl'>packman</a>."
"google earth": "Google earth is available from google's website: <a href='http://earth.google.de/download-earth.html'>http://earth.google.de/download-earth.html</a>"
"kde4": "kde4 is not a package name. Please try searching for kdebase4 for example."