development:
  secret_key_base: 'CHANGE_ME_for_som3th1ng_R4ND0M_generated_WITH_0000rake_secret0000'

test:
  secret_key_base: 'CHANGE_ME_for_som3th1ng_R4ND0M_generated_WITH_0000rake_secret0000'

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
